//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"S:\\my stuff\\OurProject.ExXD\\" +
            "Project.exxd\\Project.exxd\\AutomotiveCRM.mdf\";Integrated Security=True;Connect Ti" +
            "meout=30")]
        public string AutomotiveCRMConnectionString {
            get {
                return ((string)(this["AutomotiveCRMConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"S:\\repos\\FinalProject yes\\Fi" +
            "nalProject\\AutomotiveCRM_VehicleTable.mdf\";Integrated Security=True;Connect Time" +
            "out=30")]
        public string AutomotiveCRM_VehicleTableConnectionString {
            get {
                return ((string)(this["AutomotiveCRM_VehicleTableConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"S:\\repos\\FinalProject yes\\Fi" +
            "nalProject\\AutomotiveCRM_InvoicesTable.mdf\";Integrated Security=True;Connect Tim" +
            "eout=30")]
        public string AutomotiveCRM_InvoicesTableConnectionString {
            get {
                return ((string)(this["AutomotiveCRM_InvoicesTableConnectionString"]));
            }
        }
    }
}
